# -*- coding: utf-8 -*-
"""fusio_based_generation_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DnA5Xh-5iSeoRjZsvHEJJob7FETdGtQ
"""

!pip install rdkit

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdChemReactions
from rdkit.Chem import rdmolops
from google.colab import files
import random
import os

uploaded = files.upload()
filename = list(uploaded.keys())[0]

fragments = []
with open(filename, "r") as f:
    for line in f:
        smi = line.strip()
        mol = Chem.MolFromSmiles(smi)
        if mol:
            fragments.append(mol)

print("Fragments loaded:", len(fragments))

def safe_sanitize(mol):
    try:
        Chem.SanitizeMol(
            mol,
            sanitizeOps=Chem.SanitizeFlags.SANITIZE_ALL ^
                        Chem.SanitizeFlags.SANITIZE_KEKULIZE
        )
        return True
    except:
        return False

from rdkit import Chem

def load_fragments(file_path):
    mols = []
    with open(file_path, "r") as f:
        for line in f:
            smi = line.strip()
            if smi:
                mol = Chem.MolFromSmiles(smi)
                if mol:
                    mols.append(mol)
    return mols

fragments = load_fragments("/content/two_fused_fragments.smi")

print("Total fragments loaded:", len(fragments))

import random
from rdkit import Chem

# ---- Find valid aromatic edge pairs ----
def get_edge_pairs(mol):
    pairs = []
    for bond in mol.GetBonds():
        a1 = bond.GetBeginAtom()
        a2 = bond.GetEndAtom()

        if (
            a1.GetAtomicNum() == 6 and
            a2.GetAtomicNum() == 6 and
            a1.GetIsAromatic() and
            a2.GetIsAromatic() and
            a1.GetDegree() == 2 and
            a2.GetDegree() == 2
        ):
            pairs.append((a1.GetIdx(), a2.GetIdx()))
    return pairs


# ---- Fusion function ----
from rdkit import Chem

def fuse_true(mol1, mol2):
    pairs1 = get_edge_pairs(mol1)
    pairs2 = get_edge_pairs(mol2)

    if not pairs1 or not pairs2:
        return None

    a1, b1 = random.choice(pairs1)
    a2, b2 = random.choice(pairs2)

    mol1 = Chem.RWMol(mol1)
    mol2 = Chem.RWMol(mol2)

    # --- Step 1: combine
    combo = Chem.CombineMols(mol1, mol2)
    rw = Chem.RWMol(combo)

    offset = mol1.GetNumAtoms()
    a2_off = a2 + offset
    b2_off = b2 + offset

    try:
        # --- Step 2: get neighbors of atoms to delete (excluding each other)
        nbrs_a2 = [n.GetIdx() for n in rw.GetAtomWithIdx(a2_off).GetNeighbors() if n.GetIdx() != b2_off]
        nbrs_b2 = [n.GetIdx() for n in rw.GetAtomWithIdx(b2_off).GetNeighbors() if n.GetIdx() != a2_off]

        # --- Step 3: reconnect neighbors to mol1 atoms
        for n in nbrs_a2:
            rw.AddBond(a1, n, Chem.BondType.AROMATIC)

        for n in nbrs_b2:
            rw.AddBond(b1, n, Chem.BondType.AROMATIC)

        # --- Step 4: REMOVE the two atoms (IMPORTANT: remove higher index first)
        for idx in sorted([a2_off, b2_off], reverse=True):
            rw.RemoveAtom(idx)

        mol = rw.GetMol()

        # --- Step 5: sanitize
        if not safe_sanitize(mol):
            return None

        return mol

    except:
        return None

import random
from rdkit import Chem

target = 10000
max_attempts = 200000

generated_smiles = set()
generated_molecules = []

attempts = 0

while len(generated_smiles) < target and attempts < max_attempts:
    attempts += 1

    mol1, mol2 = random.sample(fragments, 2)

    # 🔥 TRUE fusion
    combined = fuse_true(mol1, mol2)
    if combined is None:
        continue

    # size filter
    if combined.GetNumAtoms() > 120 or combined.GetNumAtoms() < 10:
        continue

    # ---------------------------
    # FINAL VALIDITY CHECK
    # ---------------------------
    try:
        Chem.SanitizeMol(combined)
    except:
        continue

    smi = Chem.MolToSmiles(combined, canonical=True)

    if not smi or len(smi) < 5:
        continue

    if smi in generated_smiles:
        continue

    generated_smiles.add(smi)
    generated_molecules.append(combined)

    if len(generated_smiles) % 500 == 0:
        print(f"Generated: {len(generated_smiles)}")

print("\n✅ FINAL RESULT")
print("Total unique SMILES:", len(generated_smiles))
print("Total attempts:", attempts)

output_file = "/content/generated_gqds.smi"

with open(output_file, "w") as f:
    for smi in generated_smiles:
        f.write(smi + "\n")

print("Saved to:", output_file)

smi_file = "/content/generated_gqds.smi"  # <-- put your file name here

smiles_list = []
with open(smi_file, "r") as f:
    for line in f:
        smi = line.strip()
        if smi:
            smiles_list.append(smi)

print("Loaded SMILES:", len(smiles_list))

from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
import os

output_dir = "/content/gqd_images_last_500"
os.makedirs(output_dir, exist_ok=True)

for i, smi in enumerate(smiles_list[9500:]):  # use your file here
    mol = Chem.MolFromSmiles(smi)
    if mol is None:
        continue

    drawer = rdMolDraw2D.MolDraw2DCairo(400, 400)
    drawer.DrawMolecule(mol)
    drawer.FinishDrawing()

    with open(f"{output_dir}/mol_{i}.png", "wb") as f:
        f.write(drawer.GetDrawingText())

print("✅ High-quality images saved")

from google.colab import files
uploaded = files.upload()

from rdkit import Chem

input_file = "generated_gqds.smi"   # change this to your uploaded file name
output_file = "unique_smiles.smi"

unique_smiles = set()

with open(input_file, "r") as f:
    for line in f:
        smi = line.strip().split()[0]  # handles cases with extra columns
        mol = Chem.MolFromSmiles(smi)
        if mol:
            canon = Chem.MolToSmiles(mol, canonical=True)
            unique_smiles.add(canon)

# Write unique SMILES
with open(output_file, "w") as f:
    for smi in sorted(unique_smiles):
        f.write(smi + "\n")

print(f"Unique SMILES count: {len(unique_smiles)}")